package forms;

import abstratas.PopularListas;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lucas
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemCliente = new javax.swing.JMenuItem();
        itemFornecedor = new javax.swing.JMenuItem();
        itemFuncionario = new javax.swing.JMenuItem();
        itemPlataforma = new javax.swing.JMenuItem();
        itemJogo = new javax.swing.JMenuItem();
        itemSerie = new javax.swing.JMenuItem();
        itemFilme = new javax.swing.JMenuItem();
        itemProduto = new javax.swing.JMenuItem();
        itemOL = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemConsultaOL = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Locadora 2.0");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jMenu1.setText("Arquivo");

        itemCliente.setText("Cliente");
        itemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClienteActionPerformed(evt);
            }
        });
        jMenu1.add(itemCliente);

        itemFornecedor.setText("Fornecedor");
        itemFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(itemFornecedor);

        itemFuncionario.setText("Funcionário");
        itemFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(itemFuncionario);

        itemPlataforma.setText("Plataforma");
        itemPlataforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPlataformaActionPerformed(evt);
            }
        });
        jMenu1.add(itemPlataforma);

        itemJogo.setText("Jogo");
        itemJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemJogoActionPerformed(evt);
            }
        });
        jMenu1.add(itemJogo);

        itemSerie.setText("Série");
        itemSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSerieActionPerformed(evt);
            }
        });
        jMenu1.add(itemSerie);

        itemFilme.setText("Filme");
        itemFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFilmeActionPerformed(evt);
            }
        });
        jMenu1.add(itemFilme);

        itemProduto.setText("Produto");
        itemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(itemProduto);

        itemOL.setText("Ordem de locação");
        itemOL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOLActionPerformed(evt);
            }
        });
        jMenu1.add(itemOL);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        itemConsultaOL.setText("Ordem Locação");
        itemConsultaOL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultaOLActionPerformed(evt);
            }
        });
        jMenu2.add(itemConsultaOL);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClienteActionPerformed
        // TODO add your handling code here:
        new dialogCliente(this, true).setVisible(true);
    }//GEN-LAST:event_itemClienteActionPerformed

    private void itemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFornecedorActionPerformed
        // TODO add your handling code here:
        new dialogFornecedor(this, true).setVisible(true);
    }//GEN-LAST:event_itemFornecedorActionPerformed

    private void itemFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFuncionarioActionPerformed
        // TODO add your handling code here:
        new dialogFuncionario(this, true).setVisible(true);
    }//GEN-LAST:event_itemFuncionarioActionPerformed

    private void itemJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemJogoActionPerformed
        // TODO add your handling code here:
        new dialogJogo(this, true).setVisible(true);
    }//GEN-LAST:event_itemJogoActionPerformed

    private void itemPlataformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPlataformaActionPerformed
        // TODO add your handling code here:
        new dialogPlataforma(this, true).setVisible(true);
    }//GEN-LAST:event_itemPlataformaActionPerformed

    private void itemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProdutoActionPerformed
        // TODO add your handling code here:
        new dialogProduto(this, true).setVisible(true);
    }//GEN-LAST:event_itemProdutoActionPerformed

    private void itemSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSerieActionPerformed
        // TODO add your handling code here:
        new dialogSerie(this, true).setVisible(true);
    }//GEN-LAST:event_itemSerieActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        PopularListas.addDados();
    }//GEN-LAST:event_formWindowOpened

    private void itemFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFilmeActionPerformed
        // TODO add your handling code here:7
        new dialogFilme(this, true).setVisible(true);
    }//GEN-LAST:event_itemFilmeActionPerformed

    private void itemOLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOLActionPerformed
        // TODO add your handling code here:
        new dialogOrdemLocacao(this,true).setVisible(true);
    }//GEN-LAST:event_itemOLActionPerformed

    private void itemConsultaOLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultaOLActionPerformed
        // TODO add your handling code here:
        new dialogConsultaOL(this, true).setVisible(true);
    }//GEN-LAST:event_itemConsultaOLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCliente;
    private javax.swing.JMenuItem itemConsultaOL;
    private javax.swing.JMenuItem itemFilme;
    private javax.swing.JMenuItem itemFornecedor;
    private javax.swing.JMenuItem itemFuncionario;
    private javax.swing.JMenuItem itemJogo;
    private javax.swing.JMenuItem itemOL;
    private javax.swing.JMenuItem itemPlataforma;
    private javax.swing.JMenuItem itemProduto;
    private javax.swing.JMenuItem itemSerie;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
